name: ecommerce_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  dio: ^5.7.0
  http: ^1.2.2
  path_provider: ^2.0.14
  file_picker: ^8.1.4
  intl: ^0.19.0
  provider: ^6.0.5
  path: ^1.8.2
  google_fonts: ^6.2.1
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  flutter_stripe: ^11.2.0
  shared_preferences: ^2.1.0
  fluttertoast: ^8.2.8
  flutter_switch: ^0.3.2
  flutter_avif: ^2.5.0
  signalr_netcore: ^0.1.7+2-nullsafety.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
